### ISSUE TITLE
TODO LIST 140324

### ISSUE THREAD

**Issue by VincenzoPresta** [nide29/progettoMSSL#1]
Dal momento che è emersa, dall'analisi del grafico dei residui rispetto alle ordinate stimate e dai test di Breusch-Pagan e White, la presenza di eteroschedasticità all'interno del modello, ecco una "to do list" su come  procedere:
- [x] applicazione modello log-lin 
- [x] ripetizione bp e w test su quel modello, 
- [x] Modello pesato per le ordinate stimate (i regressori vengono divisi per le ordinate stimate)
- [x] ripetere bp e w test sul modello pesato per le ordinate stimate
- [x] se ancora presente eteroschedasticità si passa a un modello pesato per i regressori
- [x] ripetere bp e w test sul modello pesato per i regressori
